#!/bin/bash

up
cl
sleep 2
clear
echo

# Testing sequence for commands
# - add (fossil, git)
# - merge, split
# - current (alias @)
# - rename
# - swap
# - remove

# TODO
# - update
# - list, reset, rewind
# - submissions, accept, reject
# - debug levels

O m add http://chiselapp.com/user/andreas_kupries/repository/marpa -N marpa/chisel
F m add http://chiselapp.com/user/andreas_kupries/repository/kettle -N marpa/chisel ;# fail dup name
O m add https://core.tcl.tk/akupries/marpa/index
F m add https://core.tcl.tk/akupries/marpa/index ;# fail dup repo
O m merge
# todo merge without current, without previous and incomplete cli
O m split
O m @
F m split ;# fail - to small - core alone
O m merge
O m rename marpa
F m rename marpa ; # fail - same name
lr
F m merge ; # fail - all repos in same set
O m add http://github.com/andreas-kupries/marpa
O m debug test-vt-repo
O m swap
O m merge
O m swap
O m split
O m merge
lr
O m reset
O m rename marpa
O m @
O m swap
O m go chisel
O m remove chisel ;# repository url substring matching
O m remove core   ;# merge current/previous with the rolodex ?
O m remove github ;# a larger stack ?
O m @

# Configuration query and manipulation

O m vcs

# Here the database is empty again and all configuration values are
# back to their defaults.
