#!/bin/bash

up
cl
sleep 2
clear
echo

VERBOSE=
#VERBOSE=--verbose

O m add ${VERBOSE} git@github.com:flightaware/tclreadline FA.tclreadline
O m list
O m update ${VERBOSE} @c
O m update ${VERBOSE} @c
#O m remove @c
