#!/bin/bash

up
cl
sleep 2
clear
echo

O m submissions
O m submit https://chiselapp.com/user/andreas_kupries/repository/Kettle akupries@suse.com
O m submit https://chiselapp.com/user/andreas_kupries/repository/famfamfam akupries@suse.com Andreas
O m submissions
O m debug test-vt-submission
O m reject famfamfam
O m accept Kettle
O m submissions
O m list
O m debug test-vt-repo
O m debug test-vt-mset
#O m debug test-vt-reply
O m remove Kettle
