#!/bin/bash

up
cl
sleep 2
clear
echo

O m add http://chiselapp.com/user/andreas_kupries/repository/marpa
O m add https://core.tcl.tk/akupries/marpa/index
O m add http://github.com/andreas-kupries/marpa
#lr
O m list
O m @
