#!/bin/bash

up
cl
sleep 2
clear
echo

O m add https://github.com/andreas-kupries/marpa
O m add https://chiselapp.com/user/andreas_kupries/repository/marpa
O m merge
O m add https://core.tcl.tk/akupries/marpa/index
O m merge
O m list
O m rename marpa
O m list
O m @
O m update --verbose
