#!/bin/bash

function g ()
{
    rm $$.* 2> /dev/null

    cmd="$1"
    shift
    case "$cmd" in
	tk) gitk --all &
	    ;;
	g)  git gui &
	    ;;
	tl) # Tag List
	    git tag
	    ;;
	ta) # Tag Add
	    git tag -m "$1" "$1"
	    ;;
	td) # Tag Delete
	    git tag -d "$1"
	    ;;
	tdr) # Tag Delete Remote
	    git push origin --delete "$1"
	    ;;
	tda) # Tag Delete All
	    git tag -d "$1"
	    git push origin --delete "$1"
	    ;;
	tm) # Tag Move
	    git tag -d "$1"
	    git tag -m "$1" "$1"
	    ;;
	go) # Switch to revision, or branch
	    git checkout "$@"
	    ;;
	bl) # Branch List
	    git branch -a
	    ;;
	bc) # Branch List
	    git branch -a|grep '^\*'
	    ;;
	bn) # Branch New
	    git checkout -b "$@"
	    ;;
	bd) # Branch Delete
	    git branch -d "$@"
	    ;;
	bda) # Branch Delete All
	    git branch -d "$1"
	    git push origin --delete "$1"
	    ;;
	bdr) # Branch Delete Remote
	    git push origin --delete "$1"
	    ;;
	track) # Track Remote Branch Locally
	    # 1=local name, 2=remote 3=remote name
	    git branch --track "$1" "$2/$3"
	    ;;
	ch) # CHanges
            git status -s "$@"
	    ;;
	delta)
            git diff "$@"
	    ;;
	hi) # HIstory
            git log --oneline --graph
	    ;;
        co)  # COmmit
            message="$1"
            shift
            git commit -a -m "$message" "$@"
        ;;
	peers) # Remote List
	    git remote -v
	    ;;
	pa) # new peer/remote
	    git remote add "$1" "$2"
	    ;;
	pd) # remove peer/remote
	    git remote rm "$1"
	    ;;
	sync) # Sync
	    git push --mirror
	    git fetch -t
	    ;;
	up) # UPdate
	    clear
	    echo
	    git fetch
	    git checkout "$@"
	    echo
	    ;;
	xc)
	    repo="$@"
	    repo="${repo#https://github.com/}"
	    repo="${repo#http://github.com/}"
	    repo="${repo#git@github.com:}"
	    git hub clone "$repo"
	    r=$(basename "$repo")
	    mv $r/.git ZZ
	    rm -rf $r
	    mv ZZ $r
	    ;;
	help)
	    clear
	    echo
	    git help "$@"
	    echo
	    ;;
	*)  # All regular commands, without shortcutting
	    git $cmd "$@"
	;;
    esac
}

g "$@"
exit
