#!/bin/bash

roots="$@"

if [ "X$roots" = "X" ] ; then
    roots="$(pwd)"
fi

repos=""
have=0
for root in $roots ; do
    find "$root" -type d -print0 | (
	while read -d '' ; do
	    if ! h-is-repo "$REPLY" ; then
		continue
	    fi
	    h-fetch "$REPLY"
	done
    )
done
exit 0
