#!/bin/sh

roots="$@"

if [ "X$roots" = "X" ] ; then
    roots="$(pwd)"
fi

repos=""
have=0
for root in $roots ; do
    for d in $(find $root -type d -print) ; do
	if ! g-is-repo $d ; then
	    continue
	fi
	echo Found: $d
    done
done
exit 0
