#!/bin/bash

out="$1"

if [ "X$out" = "X" ] ; then
    echo 1>&1 "Usage: $0 path"
    exit 1
fi

# Resolve special @-links by searching in the PATH.
if [ -h "$out" ] ; then
    dst=$(readlink -n ./Update)
    case $dst in
	@*) out=$(which ${dst#@}) ;;
	*)  ;;
    esac
fi

echo $out
exit 0
