#!/bin/bash

source $(dirname "$0")/colors

if "$@"
then printf "%bFAIL. Unexpected ok.%b\n"   "${ERROR_COLOR}" "${NO_COLOR}"
else printf "%bOK__.%b Expected failure\n" "${OK_COLOR}" "${NO_COLOR}"
fi
