#!/bin/bash
echo ___________________________________________ "$@"
#export MIRROR_DEBUG
#MIRROR_DEBUG=
#MIRROR_DEBUG=${MIRROR_DEBUG},m/db
#MIRROR_DEBUG=${MIRROR_DEBUG},m/glue
#MIRROR_DEBUG=${MIRROR_DEBUG},m/mailer
#MIRROR_DEBUG=${MIRROR_DEBUG},m/match
#MIRROR_DEBUG=${MIRROR_DEBUG},m/repo
#MIRROR_DEBUG=${MIRROR_DEBUG},m/rolodex
#MIRROR_DEBUG=${MIRROR_DEBUG},m/validate/reply
#MIRROR_DEBUG=${MIRROR_DEBUG},m/vcs
#MIRROR_DEBUG=${MIRROR_DEBUG},m/vcs/fossil
#MIRROR_DEBUG=${MIRROR_DEBUG},m/vcs/git
#MIRROR_DEBUG=${MIRROR_DEBUG},m/vcs/github
./bin/mirror "$@"
